### ISSUE TITLE
NR Readonly Test

### ISSUE THREAD

**Issue by nicolleromero** [unicorns-r-us/test-repo#161]
```[tasklist]
### Tasks
- [ ] A
- [x] New draft
- [ ] https://implement-drag-between-tasklists.review-lab.github.com/unicorns-r-us/issues-graph-tests/issues/1124
```
```[tasklist]
### Tasks
- [x] C
```
```[tasklist]
### Tasks
- [x] Edit this one
- [ ] https://implement-drag-between-tasklists.review-lab.github.com/unicorns-r-us/issues-graph-tests/issues/1096
- [x] B
```
